import { TranspilerEngine } from '../compiler/transpiler/engine';
import { Artifact } from '../artifacts/schemas/sovereignArtifact';

async function testIntegration() {
    console.log("🧪 RUNNING SOVEREIGN INTEGRATION TEST...");

    const mockArtifact: Artifact = {
        uid: "SOV-999",
        name: "core_logic.ts",
        type: 'CODE',
        version: '1.0.0',
        content: "console.log('Sovereign Executing...');",
        checksum: "abc",
        createdAt: Date.now()
    };

    try {
        const source = TranspilerEngine.transpileToSource(mockArtifact);
        console.log("✅ [PASS] Transpilation & Security Check");
        if (!source.includes("GENERATED BY FEAC")) throw new Error("Missing Header");
        console.log("✅ [PASS] Industrial Header Injection");
    } catch (e) {
        console.error("❌ [FAIL] Integration Test:", e);
        process.exit(1);
    }

    console.log("✨ ALL INTEGRATION TESTS PASSED.");
}

testIntegration();
