name: FEAC Sovereign Docker Build
on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout Code (V4)
      - name: Checkout Source
        uses: actions/checkout@v4

      # Langkah 2: Build dalam Container (Mengabaikan environment Runner yang rusak)
      - name: Build with Buildozer Docker
        uses: ArtemSerebriakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer -v android debug
          buildozer_version: master
          repository_root: .

      # Langkah 3: Upload Artifact (V4 - Wajib)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FEAC-Ultimate-APK
          path: bin/*.apk
          compression-level: 0
